Login form
ZdruzenieSTROM/webstrom-frontend pull request #20
Opened 2021-04-21 11:56 UTC by tomaskocak

Pridane/zmenene veci:

**Overlay komponent:**  vytvori overlay v ktorom sa daju zobrazovat komponenty mimo obsahu stranky. Zatial sa tento overlay zobrazuje staticky nad celou strankou, neskor pridam moznost zobrazivat ho nad aktualnym html elementom v ktorom sa nachadza, bude to potrebne neskor na zobrazovanie detailov postov alebo zobrazovanie diskusii.

**Authentication komponent:** je to komponent v MenuMain ktory zobrazuje "odhlasit" button v pripade ze je uzivatel prihlaseny alebo "registrovat" a "prihlasit" buttony ktore zobrazia overlay ktory ma v strede registracny/prihlasovaci form.

**LoginForm komponent:** je to komponent ktory zabezpecuje renderovanie formu na prihlasovanie a zastresuje prihlasovanie na submit event.

**Nacitanie menu itemov:** useEffect v MenuMain, ktory nacitava menu itemy pouzival .then() syntax. Teraz sa pouziva async + await

**Axios response interceptor:** presunuty do Webstrom useEffect kde checkuje ci sa nevratil error status 401. V takom pripade zrusi prihlasovacie cookies a posle request opat.

**react-cookie package:** definuje useCookies hook ktory zabezpecuje zmenu a sledovanie cookies (podobne ako to co som robil providerom ale tu je to out of the box, tak som moj kod nahradil)

2021-05-24 22:03 UTC, rtrembecky requested changes
sorry? 🙈 
rebasni na mastra, preklikaj konflikty, no a skus sa nejak postupne prehrabat mojimi komentarmi... a ak nieco nie je jasne, pis. niekde som zachytil cely myslienkovy pochod, mozno to moze byt zmatocne 😄

2021-05-25 08:25 UTC, rtrembecky commented on src/components/Overlay/Overlay.tsx
> +  displayToggle: () => void
tu je inak nejaky standardny package `react-modal`. len pre demonstraciu, ze klasicky zaklad API takychto overlay componentov je `isOpen` a `onRequestClose`

2021-05-25 08:30 UTC, rtrembecky commented on src/components/Overlay/Overlay.tsx
> +  displayToggle: () => void
inak dalsi standard celkom je nazyvat funkcie v propoch `onXyz`, ale nie vzdy sa to uplne da 😄  pomenovat funkciove propy podla toho, pri akej akcii sa funkcia spusti, a hodnotove propy tiez podla toho, co urcuju. onRequestClose hovori "daj sem funkciu, ktora sa zavola, ked uzivatel requestne zavretie (klikom na X alebo mimo modalu)". a vkladas do toho funkciu "zavri modal" - `closeModal`

2021-06-03 14:28 UTC, tomaskocak commented on src/components/Overlay/Overlay.tsx
> +    <div className={'overlay ' + (display && 'display ')} onClick={handleClick}>
Pravda, neviem uz ani preco som mal pocit ze podmienene renderovanie nebude fungovat ale funguje :D

2021-06-07 18:00 UTC, rtrembecky approved these changes

2021-06-07 18:04 UTC, merged